In [7]:
from pathlib import Path
import pandas as pd

## Loading the data

In [ ]:
data_path = Path(r"QuestionDataV2_06122025_classified.csv").resolve()
df = pd.read_csv(data_path)
print(df.columns)

Index(['Unnamed: 0', 'Question Title', 'info.json', 'question.html',
       'server.js', 'solution.html', 'server.py', 'properties.js', 'question',
       'uuid', 'title', 'stem', 'topic', 'tags', 'prereqs', 'isAdaptive',
       'createdBy', 'qType', 'nSteps', 'updatedBy', 'difficulty', 'codelang',
       'resources', 'stepType', 'dificulty', 'relevant_courses', 'topics'],
      dtype='object')

## Inspecting

In [10]:
df.head()

,Unnamed: 0,Question Title,info.json,question.html,server.js,solution.html,server.py,properties.js,question,uuid,...,qType,nSteps,updatedBy,difficulty,codelang,resources,stepType,dificulty,relevant_courses,topics
0,0,3dMoment1,"{\r\n ""uuid"": ""8abcd91d6-64d1-4e89-b72d-ad2...",<pl-question-panel>\r\n <pl-figure file-nam...,const math = require('mathjs');\r\n// const ma...,<pl-solution-panel>\r\n <pl-figure file-nam...,NaN,NaN,determine the moment about point o in ($n \cdo...,8abcd91d6-64d1-4e89-b72d-ad2133f25b2f,...,Num,1,NaN,1.0,Javascript,NaN,NaN,NaN,"ME 010, ME 103","Static Equilibrium, Distributed Forces"
1,1,3dMoment2,"{\r\n ""uuid"": ""8abcd91d6-64d1-4e89-b72d-ad2...",<pl-question-panel>\r\n <pl-figure file-nam...,const math = require('mathjs');\r\n// const ma...,<pl-solution-panel>\r\n <pl-figure file-nam...,NaN,NaN,"Refer to the diagram labeled ""3dMoment2.png"". ...",8abcd91d6-64d1-4e89-b72d-ad2133f25b2f,...,Num,1,NaN,1.0,Javascript,NaN,NaN,NaN,"ME 103, ME 110",3D Rigid Body Mechanics
2,2,3dMoment3,"{\r\n ""uuid"": ""8abcd91d6-64d1-4e89-b72d-ad2...",<pl-question-panel>\r\n <pl-figure file-nam...,const math = require('mathjs');\r\n// const ma...,<pl-solution-panel>\r\n <pl-figure file-nam...,NaN,NaN,determine the resultant moment produced by the...,8abcd91d6-64d1-4e89-b72d-ad2133f25b2f,...,Num,1,NaN,1.0,Javascript,NaN,NaN,NaN,NaN,"Static Equilibrium, Distributed Forces"
3,3,3dMoment4,"{\r\n ""uuid"": ""8abcd91d6-64d1-4e89-b72d-ad2...",<pl-question-panel>\r\n <pl-figure file-nam...,const math = require('mathjs');\r\n// const ma...,<pl-solution-panel>\r\n <pl-figure file-nam...,NaN,NaN,determine the resultant moments produced by th...,8abcd91d6-64d1-4e89-b72d-ad2133f25b2f,...,Num,1,NaN,1.0,Javascript,NaN,NaN,NaN,"ME 010, ME 103","Statics and Mechanics, Static Equilibrium, Vec..."
4,4,Equilibrium1,"{\r\n ""uuid"": ""8abcd91d6-64d1-4e89-b72d-ad2...","<pl-question-panel>\r\n<pl-figure file-name=""3...",const math = require('mathjs');\r\n// const ma...,<pl-solution-panel>\r\n <pl-figure file-nam...,NaN,NaN,compute the missing force vector that will all...,8abcd91d6-64d1-4e89-b72d-ad2133f25b2f,...,Num,1,NaN,1.0,Javascript,NaN,NaN,NaN,ME 010,"Static Equilibrium, Vector Analysis"

In [ ]:
columns_to_keep = [
    "Question Title",
    "question.html",
    "server.js",
    "solution.html",
    "server.py",
    "properties.js",
    "info.json",
    "isAdaptive",
]
df = df[columns_to_keep]
df.head()

,Question Title,question.html,server.js,solution.html,server.py,properties.js,info.json,isAdaptive
0,3dMoment1,<pl-question-panel>\r\n <pl-figure file-nam...,const math = require('mathjs');\r\n// const ma...,<pl-solution-panel>\r\n <pl-figure file-nam...,NaN,NaN,"{\r\n ""uuid"": ""8abcd91d6-64d1-4e89-b72d-ad2...",True
1,3dMoment2,<pl-question-panel>\r\n <pl-figure file-nam...,const math = require('mathjs');\r\n// const ma...,<pl-solution-panel>\r\n <pl-figure file-nam...,NaN,NaN,"{\r\n ""uuid"": ""8abcd91d6-64d1-4e89-b72d-ad2...",True
2,3dMoment3,<pl-question-panel>\r\n <pl-figure file-nam...,const math = require('mathjs');\r\n// const ma...,<pl-solution-panel>\r\n <pl-figure file-nam...,NaN,NaN,"{\r\n ""uuid"": ""8abcd91d6-64d1-4e89-b72d-ad2...",True
3,3dMoment4,<pl-question-panel>\r\n <pl-figure file-nam...,const math = require('mathjs');\r\n// const ma...,<pl-solution-panel>\r\n <pl-figure file-nam...,NaN,NaN,"{\r\n ""uuid"": ""8abcd91d6-64d1-4e89-b72d-ad2...",True
4,Equilibrium1,"<pl-question-panel>\r\n<pl-figure file-name=""3...",const math = require('mathjs');\r\n// const ma...,<pl-solution-panel>\r\n <pl-figure file-nam...,NaN,NaN,"{\r\n ""uuid"": ""8abcd91d6-64d1-4e89-b72d-ad2...",True

### IsAdaptive Check

In [ ]:
row_num, col_num = df.shape
adaptive_questions_count = df["isAdaptive"].sum()
print(
    f"""The number of adaptive questions is {adaptive_questions_count} \n while non adaptive questions are {row_num-adaptive_questions_count}
"""
)
py_filtered = df[(df["isAdaptive"]) & (df["server.py"].notna())]
js_filtered = df[(df["isAdaptive"]) & (df["server.js"].notna())]

The number of adaptive questions is 158
 while non adaptive questions are 105

In [23]:
import re
import json
pattern = r"</pl-[a-z\-]+>"
question_examples = {}
for text in df["question.html"]:
    result = re.findall(pattern, text)
    for r in result:
        if not question_examples.get(r, None):
            question_examples[r] = text

save_path = Path(r"example_questions.json").resolve()
print(save_path)
save_path.write_text(json.dumps(question_examples))
print(question_examples)

C:\Github\GestatlQuestions\backend\src\data\example_questions.json
{'</pl-figure>': '<pl-question-panel>\r\n    <pl-figure file-name="3dMoment1.png"></pl-figure>\r\n   <p>Determine the moment about point O in (${{params.unitsForce}} {{params.unitsDist}}$) caused by the force $ \\mathbf{F} = {{params.force}}$ $ {{params.unitsForce}}$ acting on the beam.</p>\r\n   <p>Let the lengths $\\mathbf{L}_1 = {{params.l1}}$ $ {{params.unitsDist}} $, $\\mathbf{L}_2 = {{params.l2}}$ $ {{params.unitsDist}} $, $\\mathbf{L}_3 = {{params.l3}}$ $ {{params.unitsDist}} $</p>\r\n   <p>and $\\mathbf{V}_1 = {{params.v1}}$ $ {{params.unitsDist}} $, $\\mathbf{V}_2 = {{params.v2}}$ $ {{params.unitsDist}} $, $\\mathbf{V}_3 = {{params.v3}}$ $ {{params.unitsDist}} $</p>\r\n</pl-question-panel>\r\n\r\n<pl-number-input answers-name="momenti" comparison="sigfig" digits="3" label="Moment about point O $\\hat{i}$ ="></pl-number-input>\r\n<pl-number-input answers-name="momentj" comparison="sigfig" digits="3" label="Moment about point O $\\hat{j}$ ="></pl-number-input>\r\n<pl-number-input answers-name="momentk" comparison="sigfig" digits="3" label="Moment about point O $\\hat{k}$ ="></pl-number-input>', '</pl-question-panel>': '<pl-question-panel>\r\n    <pl-figure file-name="3dMoment1.png"></pl-figure>\r\n   <p>Determine the moment about point O in (${{params.unitsForce}} {{params.unitsDist}}$) caused by the force $ \\mathbf{F} = {{params.force}}$ $ {{params.unitsForce}}$ acting on the beam.</p>\r\n   <p>Let the lengths $\\mathbf{L}_1 = {{params.l1}}$ $ {{params.unitsDist}} $, $\\mathbf{L}_2 = {{params.l2}}$ $ {{params.unitsDist}} $, $\\mathbf{L}_3 = {{params.l3}}$ $ {{params.unitsDist}} $</p>\r\n   <p>and $\\mathbf{V}_1 = {{params.v1}}$ $ {{params.unitsDist}} $, $\\mathbf{V}_2 = {{params.v2}}$ $ {{params.unitsDist}} $, $\\mathbf{V}_3 = {{params.v3}}$ $ {{params.unitsDist}} $</p>\r\n</pl-question-panel>\r\n\r\n<pl-number-input answers-name="momenti" comparison="sigfig" digits="3" label="Moment about point O $\\hat{i}$ ="></pl-number-input>\r\n<pl-number-input answers-name="momentj" comparison="sigfig" digits="3" label="Moment about point O $\\hat{j}$ ="></pl-number-input>\r\n<pl-number-input answers-name="momentk" comparison="sigfig" digits="3" label="Moment about point O $\\hat{k}$ ="></pl-number-input>', '</pl-number-input>': '<pl-question-panel>\r\n    <pl-figure file-name="3dMoment1.png"></pl-figure>\r\n   <p>Determine the moment about point O in (${{params.unitsForce}} {{params.unitsDist}}$) caused by the force $ \\mathbf{F} = {{params.force}}$ $ {{params.unitsForce}}$ acting on the beam.</p>\r\n   <p>Let the lengths $\\mathbf{L}_1 = {{params.l1}}$ $ {{params.unitsDist}} $, $\\mathbf{L}_2 = {{params.l2}}$ $ {{params.unitsDist}} $, $\\mathbf{L}_3 = {{params.l3}}$ $ {{params.unitsDist}} $</p>\r\n   <p>and $\\mathbf{V}_1 = {{params.v1}}$ $ {{params.unitsDist}} $, $\\mathbf{V}_2 = {{params.v2}}$ $ {{params.unitsDist}} $, $\\mathbf{V}_3 = {{params.v3}}$ $ {{params.unitsDist}} $</p>\r\n</pl-question-panel>\r\n\r\n<pl-number-input answers-name="momenti" comparison="sigfig" digits="3" label="Moment about point O $\\hat{i}$ ="></pl-number-input>\r\n<pl-number-input answers-name="momentj" comparison="sigfig" digits="3" label="Moment about point O $\\hat{j}$ ="></pl-number-input>\r\n<pl-number-input answers-name="momentk" comparison="sigfig" digits="3" label="Moment about point O $\\hat{k}$ ="></pl-number-input>', '</pl-number-input-fixed>': '<pl-question-panel>\r\n  <pl-figure file-name="3DReaction5.JPG"></pl-figure>\r\n  <p>\r\n   A 450-lb load hangs from the corner $C$ of a rigid piece of pipe $ABCD$ that has been bent as shown. The pipe is supported by ball-and-socket joints $A$ and $D$, and by a cable attached at the midpoint $E$ of the portion $BC$ of the pipe and at point $G$ on the wall. Determine (a) where $G$ should be located if the tension in the cable is to be minimum, (b) the corresponding minimum value of tension.\r\n </p>\r\n</pl-question-panel>\r\n\r\n<p> The x-coordinate of the location of G ($G_X$) is equal to: </p>\r\n<pl-number-input-fixed answers-name="G_X" correct-answer-fixed="0" comparison="sigfig" digits="1" label="$G_{X}$ (ft)"></pl-number-input-fixed>\r\n\r\n<p> The y-coordinate of the location of G ($G_Y$) is equal to: </p>\r\n<pl-number-input-fixed answers-name="G_Y" correct-answer-fixed="15" comparison="sigfig" digits="2" label="$G_{Y}$ (ft)"></pl-number-input-fixed>\r\n\r\n<p> The minimum value of tension ($T_{min}$) is equal to:</p>\r\n<pl-number-input-fixed answers-name="T_{min}" correct-answer-fixed="300" comparison="sigfig" digits="3" label="$T_{min}$ (lb)"></pl-number-input-fixed>\r\n\r\n', '</pl-answer>': '<pl-question-panel>\r\n  <pl-figure file-name="DistForce3.jpg"></pl-figure>\r\n  <p>\r\n  The gate is hinged at pin O and has a distributed load as shown. It is propped at A by means of a rod AB hinged at both A and B. \r\n </p>\r\n</pl-question-panel>\r\n\r\n<p> The force that is equivalent to the distributed force has a magnitude of ______ kN </p>\r\n<pl-number-input-fixed answers-name="Feq" correct-answer-fixed="30" comparison="sigfig" digits="3" label="$F_{eq}$ (kN)"></pl-number-input-fixed>\r\n<p> The equivalent force $F_{eq}$ passes through a point located a distance of __________ m vertically above point O.  </p>\r\n<pl-number-input-fixed answers-name="Dist" correct-answer-fixed="2" comparison="sigfig" digits="3" label=" m "></pl-number-input-fixed>\r\n\r\n\r\n\r\n<pl-question-panel> \r\n<p>What is the force at A on the gate?</p>\r\n<pl-multiple-choice answers-name="ForceA" weight="1" inline="true">\r\n  <pl-answer correct="true">24 kN directed towards A  </pl-answer>\r\n  <pl-answer correct="false">24 kN directed away from A  </pl-answer>\r\n  <pl-answer correct="false"> 18 kN directed towards A  </pl-answer>\r\n  <pl-answer correct="false"> 18 kN directed away from A  </pl-answer>\r\n</pl-multiple-choice>', '</pl-multiple-choice>': '<pl-question-panel>\r\n  <pl-figure file-name="DistForce3.jpg"></pl-figure>\r\n  <p>\r\n  The gate is hinged at pin O and has a distributed load as shown. It is propped at A by means of a rod AB hinged at both A and B. \r\n </p>\r\n</pl-question-panel>\r\n\r\n<p> The force that is equivalent to the distributed force has a magnitude of ______ kN </p>\r\n<pl-number-input-fixed answers-name="Feq" correct-answer-fixed="30" comparison="sigfig" digits="3" label="$F_{eq}$ (kN)"></pl-number-input-fixed>\r\n<p> The equivalent force $F_{eq}$ passes through a point located a distance of __________ m vertically above point O.  </p>\r\n<pl-number-input-fixed answers-name="Dist" correct-answer-fixed="2" comparison="sigfig" digits="3" label=" m "></pl-number-input-fixed>\r\n\r\n\r\n\r\n<pl-question-panel> \r\n<p>What is the force at A on the gate?</p>\r\n<pl-multiple-choice answers-name="ForceA" weight="1" inline="true">\r\n  <pl-answer correct="true">24 kN directed towards A  </pl-answer>\r\n  <pl-answer correct="false">24 kN directed away from A  </pl-answer>\r\n  <pl-answer correct="false"> 18 kN directed towards A  </pl-answer>\r\n  <pl-answer correct="false"> 18 kN directed away from A  </pl-answer>\r\n</pl-multiple-choice>', '</pl-checkbox>': '<pl-question-panel> \r\n  <pl-figure file-name="SimpFrame.jpg"></pl-figure>\r\n\r\n<p> In the figure below, a weight W is suspended from point D of a beam AD. The beam is held up by rod BC. Neglect the mass of the beam AD and rod BC. Which of the following is true (mark all that apply)\r\n</p>\r\n\r\n<pl-checkbox answers-name="SimpFrame1" weight="1" inline="true">\r\n  <pl-answer correct="false"> The magnitude of the force in rod BC is known  </pl-answer>\r\n  <pl-answer correct="false"> The direction of the force in rod BC (i.e whether the force is tension or compression) is known.  </pl-answer>\r\n  <pl-answer correct="false"> Beam AD is a two-force member    </pl-answer>\r\n  <pl-answer correct="true">  Beam AD is a three force member  </pl-answer>\r\n  <pl-answer correct="true"> Rod BC is a two-force member   </pl-answer>\r\n  <pl-answer correct="true">  The line of action of the force in rod BC is known  </pl-answer>\r\n</pl-checkbox>', '</pl-mca-adaptive>': '<pl-question-panel> If $ a = {{params.a}} $ and $ b = {{params.b}} $, then  which of the following is true?</pl-question-panel></p>\r\n\r\n<pl-mca-adaptive> \r\n<pl-checkbox answers-name="summc" weight="1" inline="true">\r\n  <pl-answer choice-name="opt0" correct="false"> $ a + b = {{params.summc.opt0}} $ </pl-answer>\r\n  <pl-answer choice-name="opt1" correct="true"> $ a - b = {{params.summc.opt1}} $ </pl-answer>\r\n  <pl-answer choice-name="opt2" correct="false"> $ a \\times b =  {{params.summc.opt2}} $</pl-answer>\r\n  <pl-answer choice-name="opt3" correct="true"> $ a^2 = {{params.summc.opt3}} $</pl-answer>\r\n</pl-checkbox>\r\n</pl-mca-adaptive>\r\n\r\n', '</pl-mcq-adaptive>': '<pl-question-panel> If $ a = {{params.a}} $ and $ b = {{params.b}} $, then  which of the following is true?</pl-question-panel></p>\r\n\r\n<pl-mca-adaptive> \r\n<pl-checkbox answers-name="summa" weight="1" inline="true">\r\n  <pl-answer choice-name="opt0" correct="false"> $ a + b = {{params.summa.opt0}} $ </pl-answer>\r\n  <pl-answer choice-name="opt1" correct="true"> $ a - b = {{params.summa.opt1}} $ </pl-answer>\r\n  <pl-answer choice-name="opt2" correct="false"> $ a \\times b =  {{params.summa.opt2}} $</pl-answer>\r\n  <pl-answer choice-name="opt3" correct="true"> $ a^2 = {{params.summa.opt3}} $</pl-answer>\r\n</pl-checkbox>\r\n</pl-mca-adaptive>\r\n\r\n<p> \r\nIf $ a = {{params.a}} $ and $ b = {{params.b}} $, then  which of the following is true about $ b^2 $? \r\n</p>\r\n<pl-mcq-adaptive> \r\n  <pl-multiple-choice answers-name="summc" weight="1" inline="true">\r\n    <pl-answer choice-name="opt0" correct="false"> {{params.summc.opt0}} </pl-answer>\r\n    <pl-answer choice-name="opt1" correct="true"> {{params.summc.opt1}} </pl-answer>\r\n    <pl-answer choice-name="opt2" correct="false"> {{params.summc.opt2}} </pl-answer>\r\n    <pl-answer choice-name="opt3" correct="true"> {{params.summc.opt3}} </pl-answer>\r\n    <pl-answer choice-name="opt4" correct="true"> {{params.summc.opt4}} </pl-answer>\r\n  </pl-multiple-choice>\r\n  </pl-mcq-adaptive>\r\n\r\n<p> What is the value of $ a^2 - 2 $?</p> \r\n\r\n<pl-number-input answers-name="c" comparison="sigfig" digits="3" label="$c=$"></pl-number-input>\r\n\r\n\r\n', '</pl-prompt>': '<pl-question-panel>\r\n  <p> Consider two numbers $a = {{params.a}}$ and $b = {{params.b}}$.</p>\r\n</pl-question-panel>\r\n\r\n<pl-quest> \r\n<pl-quest-prompt >What is the sum $c = a + b$? </pl-prompt>\r\n<pl-number-input answers-name="c" comparison="sigfig" digits="3" label="$c=$"></pl-number-input>\r\n</pl-quest> \r\n\r\n<pl-quest> \r\n  <pl-quest-prompt >What is the sum $c = a - b$? </pl-prompt>\r\n  <pl-number-input answers-name="d" comparison="sigfig" digits="3" label="$c=$"></pl-number-input>\r\n</pl-quest> \r\n\r\n<pl-quest> \r\n    <pl-quest-prompt >What is the sum $c = a \\times  b$? </pl-prompt>\r\n    <pl-number-input answers-name="e" comparison="sigfig" digits="3" label="$c=$"></pl-number-input>\r\n</pl-quest> \r\n\r\n<pl-quest> \r\n  <pl-quest-prompt >What is the sum $c = a /  b$? </pl-prompt>\r\n  <pl-number-input answers-name="f" comparison="sigfig" digits="3" label="$c=$"></pl-number-input>\r\n</pl-quest> \r\n\r\n<pl-quest> \r\n  <pl-quest-prompt >What is the sum $c = a^2$? </pl-prompt>\r\n  <pl-number-input answers-name="g" comparison="sigfig" digits="3" label="$c=$"></pl-number-input>\r\n</pl-quest> \r\n\r\n<pl-quest> \r\n  <pl-quest-prompt >What is the sum $c = b^2$? </pl-prompt>\r\n  <pl-number-input answers-name="h" comparison="sigfig" digits="3" label="$c=$"></pl-number-input>\r\n</pl-quest> ', '</pl-quest>': '<pl-question-panel>\r\n  <p> Consider two numbers $a = {{params.a}}$ and $b = {{params.b}}$.</p>\r\n</pl-question-panel>\r\n\r\n<pl-quest> \r\n<pl-quest-prompt >What is the sum $c = a + b$? </pl-prompt>\r\n<pl-number-input answers-name="c" comparison="sigfig" digits="3" label="$c=$"></pl-number-input>\r\n</pl-quest> \r\n\r\n<pl-quest> \r\n  <pl-quest-prompt >What is the sum $c = a - b$? </pl-prompt>\r\n  <pl-number-input answers-name="d" comparison="sigfig" digits="3" label="$c=$"></pl-number-input>\r\n</pl-quest> \r\n\r\n<pl-quest> \r\n    <pl-quest-prompt >What is the sum $c = a \\times  b$? </pl-prompt>\r\n    <pl-number-input answers-name="e" comparison="sigfig" digits="3" label="$c=$"></pl-number-input>\r\n</pl-quest> \r\n\r\n<pl-quest> \r\n  <pl-quest-prompt >What is the sum $c = a /  b$? </pl-prompt>\r\n  <pl-number-input answers-name="f" comparison="sigfig" digits="3" label="$c=$"></pl-number-input>\r\n</pl-quest> \r\n\r\n<pl-quest> \r\n  <pl-quest-prompt >What is the sum $c = a^2$? </pl-prompt>\r\n  <pl-number-input answers-name="g" comparison="sigfig" digits="3" label="$c=$"></pl-number-input>\r\n</pl-quest> \r\n\r\n<pl-quest> \r\n  <pl-quest-prompt >What is the sum $c = b^2$? </pl-prompt>\r\n  <pl-number-input answers-name="h" comparison="sigfig" digits="3" label="$c=$"></pl-number-input>\r\n</pl-quest> ', '</pl-matrix-latex>': '<pl-question-panel>\r\n  <p>\r\n  Consider the two matrices:\r\n  </p>\r\n  \r\n  <p>\r\n  ${\\bf A} = <pl-matrix-latex params-name="A" digits={{params.nDigits}}></pl-matrix-latex>$\r\n  </p>\r\n  \r\n  and \r\n  <p>\r\n  ${\\bf b} = <pl-matrix-latex params-name="b" digits={{params.nDigits}}></pl-matrix-latex>$\r\n  </p>\r\n  \r\n\r\n  If $ \\mathbf{A}x = \\mathbf{b} $, what is $ x $? Express your answer in the form of a column vector.\r\n  </p>\r\n  </pl-question-panel>\r\n  \r\n  <pl-matrix-input answers-name="x" comparison="sigfig" digits={{params.sigfigs}} label="$ x  =$"></pl-matrix-input>\r\n\r\n\r\n', '</pl-matrix-input>': '<pl-question-panel>\r\n  <p>\r\n  Consider the two matrices:\r\n  </p>\r\n  \r\n  <p>\r\n  ${\\bf A} = <pl-matrix-latex params-name="A" digits={{params.nDigits}}></pl-matrix-latex>$\r\n  </p>\r\n  \r\n  and \r\n  <p>\r\n  ${\\bf b} = <pl-matrix-latex params-name="b" digits={{params.nDigits}}></pl-matrix-latex>$\r\n  </p>\r\n  \r\n\r\n  If $ \\mathbf{A}x = \\mathbf{b} $, what is $ x $? Express your answer in the form of a column vector.\r\n  </p>\r\n  </pl-question-panel>\r\n  \r\n  <pl-matrix-input answers-name="x" comparison="sigfig" digits={{params.sigfigs}} label="$ x  =$"></pl-matrix-input>\r\n\r\n\r\n', '</pl-static-text>': '<pl-question-panel>\r\n  <p>\r\n  Consider the  matrix:\r\n  </p>\r\n  <p>\r\n  $ \\mathbf{A} = <pl-matrix-latex params-name="A" digits={{params.nDigits}}></pl-matrix-latex> $\r\n  </p>\r\n  \r\n <p> \r\n  Perform LU decomposition with partial pivoting at each step.   \r\n  </p>\r\n  <p>\r\n    Write down the permutation matrix (P), lower triangular matrix (L) and upper triangular matrix (U) at each step. \r\n  </p>\r\n  </pl-question-panel>\r\n\r\n  <pl-static-text name="stepNumber"> <h4> Iteration 1 </h4> </pl-static-text>\r\n  \r\n  <pl-matrix-input answers-name="P" comparison="sigfig" digits={{params.sigfigs}} label="${\\bf P} =$"></pl-matrix-input>\r\n  <pl-matrix-input answers-name="L" comparison="sigfig" digits={{params.sigfigs}} label="${\\bf L} =$"></pl-matrix-input>\r\n  <pl-matrix-input answers-name="U" comparison="sigfig" digits={{params.sigfigs}} label="${\\bf U} =$"></pl-matrix-input>\r\n\r\n\r\n'}

## Notes

- info.json: Originally held question metadata, now empty. Not essential for generation but should be repopulated.
- question.html: HTML template that renders the student-facing question (figures, inputs, choices, etc.).
- server files: Backend logic written in either JavaScript or Python.
  -Total questions: 320 (used for semantic search); not guaranteed to reflect the current total.
- Adaptive questions: 158 — dynamically generated (e.g. numerical computations).
- Non-adaptive questions: 162 — static (e.g. multiple choice).
- Code files: 7 Python files, 139 JavaScript files related to questions.